;; -*- lexical-binding: t; -*-

;; Contains many QOL and aesthetic improvements, except theme
;; Most are nice to have, but not necessary. They should be the first
;; to be removed should there be performance/cleanups
;; Theme remains in init.el

(use-package nerd-icons
  :config
  (setq nerd-icons-font-family "Symbols Nerd Font Mono"))

(use-package nerd-icons-completion
  :after marginalia
  :config
  (nerd-icons-completion-marginalia-setup))

;; No nerd-icons-dired here: dirvish draws dired's icons itself via its
;; `nerd-icons' attribute, and running both double-renders every line.

(use-package nerd-icons-ibuffer
  :hook (ibuffer-mode . nerd-icons-ibuffer-mode))

(use-package nerd-icons-corfu
  :after corfu
  :config (add-to-list 'corfu-margin-formatters #'nerd-icons-corfu-formatter))

;; Modeline. The reason for a package here is meow: modal state is the single
;; most-consulted piece of state in this config, and the default modeline
;; renders it as unstyled text in a bar there is otherwise no reason to read.
;;
;; Left stock on purpose. Segment trimming (`mood-line-defformat') and any face
;; work against doric belong in a later pass, once there is something to react
;; to rather than a guess.
(use-package mood-line
  :config
  ;; Unicode rather than the nerd-font glyph set. This daemon serves pgtk GUI
  ;; frames and real tty frames from one process, and these render the same in
  ;; both. `mood-line-glyphs-ascii' is the fallback if anything boxes in foot.
  ;;
  ;; setq in :config, not :custom: the value is a variable defined by the
  ;; package, so it cannot be read before the package loads.
  (setq mood-line-glyph-alist mood-line-glyphs-unicode)
  (mood-line-mode))

;; Better buffer but more detailed, built-in
(use-package ibuffer
  :ensure nil
  :bind
  ([remap list-buffers] . ibuffer))

(use-package ibuffer-project
  :after ibuffer
  :hook
  (ibuffer . (lambda ()
               (setq ibuffer-filter-groups (ibuffer-project-generate-filter-groups))
               (unless (eq ibuffer-sorting-mode 'project-file-relative)
                 (ibuffer-do-sort-by-project-file-relative)))))

(use-package paren ;; Supposed to help with paren highlights
  :custom
  (show-paren-delay 0.1)
  (show-paren-highlight-openparen t)
  (show-paren-when-point-in-periphery t)
  (show-paren-when-point-inside-paren t)
  :config
  (show-paren-mode 1))

(use-package rainbow-delimiters
  :hook (prog-mode . rainbow-delimiters-mode)) ;; prog-mode is the base mode for all modes

;; dirvish is dired with a preview pane and a parent column: the yazi layout
;; without giving up dired, because it is dired -- every dired verb still
;; works. It replaces two packages rather than joining them. nerd-icons-dired
;; is gone above, and dired-subtree is gone here because dirvish ships its own
;; dirvish-subtree extension, pulled in by the `subtree-state' attribute below.
;;
;; Previews are generated by external programs (vipsthumbnail, pdftoppm,
;; ffmpegthumbnailer, mediainfo, 7z), installed in home/modules/packages.nix.
;; dirvish probes for each at runtime and drops the dispatcher when its binary
;; is absent, so `dirvish-preview-dispatchers' is deliberately left at its
;; default rather than trimmed to what happens to be installed today.
;;
;; No meow-mode-state-list entry is needed: dired-mode is neither text- nor
;; prog-derived, so meow already falls back to motion state for it, and
;; dirvish-mode derives from dired-mode. dirvish's single-letter keys reach
;; their commands rather than hitting normal state's (suppress-keymap map t).
(use-package dirvish
  ;; Required. `:bind' alone implies `:defer t', which would hold the package
  ;; back until C-c p d was pressed -- and `dirvish-override-dired-mode' below
  ;; would not have run, so C-x d would still open plain dired.
  :demand t
  :custom
  ;; Upstream ships (file-size) alone, so icons are an explicit opt-in. This
  ;; line is what replaces nerd-icons-dired.
  (dirvish-attributes '(nerd-icons file-size collapse subtree-state vc-state))
  (dirvish-quick-access-entries
   '(("h" "~/"          "home")
     ("n" "~/nixos/"    "nixos")
     ("o" "~/org/"      "org")
     ("r" "~/org/roam/" "roam")))
  :bind
  (;; `d' is the only free letter left under the C-c p project prefix, and a
   ;; project file tree belongs there. which-key already labels C-c p.
   ("C-c p d" . dirvish-side)
   :map dirvish-mode-map
   ("<backtab>" . dirvish-subtree-toggle))
  :config
  (dirvish-override-dired-mode))

(use-package project
  :bind
  ("C-c p B" . project-list-buffers)
  ("C-c p k" . project-kill-buffers))

(provide 'qol)
