#!/bin/sh

select="$(
    fd -a -I -e pdf -e epub --full-path . $HOME'/200_reading/' |
    sed "s|^${HOME}/200_reading/||" |
    fuzzel --dmenu -w 50
)" || exit 0

[ -n "$select" ] || exit 0

filepath="$HOME/200_reading/$select"

setsid -f env sioyek "$filepath" >/tmp/sioyek.log 2>&1 </dev/null 
