#!/usr/bin/env bash

directory=${1:-"$PWD"}

if ! url=$(git -C "$directory" remote get-url origin 2>/dev/null); then
  printf 'open-github: %s is not in a Git repository with an origin remote\n' \
    "$directory" >&2
  exit 1
fi

case "$url" in
  git@*:*)
    remote=${url#git@}
    host=${remote%%:*}
    path=${remote#*:}
    ;;
  ssh://git@*/*)
    remote=${url#ssh://git@}
    host=${remote%%/*}
    path=${remote#*/}
    ;;
  http://*/* | https://*/*)
    remote=${url#*://}
    host=${remote%%/*}
    path=${remote#*/}
    ;;
  *)
    printf 'open-github: unsupported origin URL: %s\n' "$url" >&2
    exit 1
    ;;
esac

case "$host" in
  github.com | codeberg.org | git.sr.ht) ;;
  *)
    printf 'open-github: unsupported forge host: %s\n' "$host" >&2
    exit 1
    ;;
esac

path=${path%.git}
if [[ -z $path || $path == "$host" ]]; then
  printf 'open-github: malformed origin URL: %s\n' "$url" >&2
  exit 1
fi

exec xdg-open "https://$host/$path"
