#!/bin/sh

choice=$(
    printf '%s\n' "Lock" "Reboot" "Shutdown" |
        fuzzel --dmenu --minimal-lines
)

case "$choice" in
    Lock)
        lock-screen
        ;;
    Shutdown)
        systemctl poweroff
        ;;
    Reboot)
        reboot
        ;;
esac
