#!/bin/sh
# Whole screen. See screenshot-region for a selection.

dir="${SCREENSHOT_DIR:-$HOME/screenshots}"
mkdir -p "$dir"

file="$dir/$(date +%Y%m%d_%H%M%S).png"

grim "$file" &&
    wl-copy --type image/png < "$file"
