#!/bin/sh
# Drag out a region. See screenshot-full for the whole screen.

dir="${SCREENSHOT_DIR:-$HOME/screenshots}"
mkdir -p "$dir"

geometry=$(slurp) || exit 0
file="$dir/$(date +%Y%m%d_%H%M%S).png"

grim -g "$geometry" "$file" &&
    wl-copy --type image/png < "$file"
