#!/bin/sh

select="$(
  fd -I -e pdf -e epub --strip-cwd-prefix . |
    sk --tmux center,80%
)" || exit 0

[ -n "$select" ] || exit 0

filepath="$PWD/$select"

setsid -f sioyek "$filepath" >/tmp/sioyek.log 2>&1 </dev/null
